# Generated by Django 4.2.1 on 2023-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyFatPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField()),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('neck', models.FloatField()),
                ('chest', models.FloatField()),
                ('abdomen', models.FloatField()),
                ('hip', models.FloatField()),
                ('thigh', models.FloatField()),
                ('knee', models.FloatField()),
                ('ankle', models.FloatField()),
                ('biceps', models.FloatField()),
                ('forearm', models.FloatField()),
                ('wrist', models.FloatField()),
                ('predicted_bodyfat', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
